name: Push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
on:
  push:
    branches: [main]
    paths:
      - "projects/**"
      - "cli/**"
      - ".github/**"
jobs:
  build-all:
    name: Build and deploy
    runs-on: ubuntu-latest
    outputs:
      branch-slug: ${{ env.BRANCH_SLUG }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          echo "{BRANCH_NAME}={$(echo ${GITHUB_REF#refs/heads/})}" >> $GITHUB_OUTPUT
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup Mambaforge
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     miniforge-variant: Mambaforge
      #     miniforge-version: latest
      #     activate-environment: edbook
      #     use-mamba: true
      - name: Check for Conda cache
        id: conda-cache
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{hashFiles('environment.yml')}}
      - uses: conda-incubator/setup-miniconda@v2
        if: steps.conda-cache.outputs.cache-hit != 'true'
        with:
          activate-environment: edbook
          environment-file: environment.yml
          python-version: 3.10.10
          channels: conda-forge,defaults
          mamba-version: "*"
          channel-priority: true
          use-mamba: true
      - run: |
          conda activate edbook
          conda info
          conda list
      - name: 📂 Prepare files for Github pages
        run: |
          mv _build/forsida/* _build/
      - name: Checkout edbook.github.io
        uses: actions/checkout@v3
        with:
          repository: 'edbook/edbook.github.io'
          path: org-repo
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Push to edbook.github.io
        run: |
          mv _build/* org-repo/
          cd org-repo
          ls -al
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ci: testing _build output commit"
          git push

  notify-discord-merge:
    needs: [build-all]
    name: Notify Discord (merged to main)
    runs-on: ubuntu-20.04
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Notify merge
        run: |
          content_title="Ný útgáfa er kominn í loftið 🎉"
          title="${{ github.base_ref }} ↩️ ${{ github.head_ref }}"
          color=32768
          description="${{ github.event.pull_request.body }}"
          url=${{ github.event.pull_request.html_url }}
          author_name=${{ github.event.pull_request.user.login}}
          author_url=${{ github.event.pull_request.user.url}}
          author_avatar=${{ github.event.pull_request.user.avatar_url}}
          branch=${{ github.head_ref }}

          payload=$(cat <<EOF
          {
            "content": "$content_title",
            "avatar_url": "https://www.shareicon.net/data/128x128/2015/08/28/92005_social-media_512x512.png",
            "embeds": [
              {
                "title": "$title",
                "description": "$description",
                "url": "$url",
                "color": $color,
                "fields": [
                  "name": "url",
                  "value": "[Skoða á edbook](https://edbook.hi.is)"
                ]
                "author": {
                  "name": "$author_name",
                  "url": "$author_url",
                  "icon_url": "$author_avatar"
                }
              }
            ]
          }
          EOF
          )
          ./.github/discord.sh  \
            -w ${{ secrets.DISCORD_WEBHOOK }} \
            -c "$payload"

  notify-discord-build-failed:
    needs: [build-all]
    if: always() && needs.build-all.result == 'failure' && github.event_name == 'push'
    name: Notify Discord (build failed)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Notify build or deploy failed
        run: |
          workflow_url="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          content_title="Eitthvað fór úrskeiðis ☠️"
          title="${{ env.BRANCH_NAME }}"
          color=16711680
          description="Ekki tókst að byggja og/eða deploya branchinu _${{ env.BRANCH_NAME }}_"
          url="$workflow_url"
          author_name=${{ github.event.push.sender.login}}
          author_url=${{ github.event.push.sender.url}}
          author_avatar=${{ github.event.push.sender.avatar_url}}

          payload=$(cat <<EOF
          {
            "content": "$content_title",
            "avatar_url": "https://www.shareicon.net/data/128x128/2015/08/28/92005_social-media_512x512.png",
            "embeds": [
              {
                "title": "$title",
                "description": "$description",
                "url": "$url",
                "color": $color,
                "author": {
                  "name": "$author_name",
                  "url": "$author_url",
                  "icon_url": "$author_avatar"
                }
              }
            ]
          }
          EOF
          )
          ./.github/discord.sh  \
            -w ${{ secrets.DISCORD_WEBHOOK }} \
            -c "$payload"
